// Code generated by MockGen. DO NOT EDIT.
// Source: app/repositories/role.go

package mocks

import (
	gomock "github.com/golang/mock/gomock"
	models "github.com/quangdangfit/go-admin/app/models"
	reflect "reflect"
)

// MockIRoleRepository is a mock of IRoleRepository interface
type MockIRoleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIRoleRepositoryMockRecorder
}

// MockIRoleRepositoryMockRecorder is the mock recorder for MockIRoleRepository
type MockIRoleRepositoryMockRecorder struct {
	mock *MockIRoleRepository
}

// NewMockIRoleRepository creates a new mock instance
func NewMockIRoleRepository(ctrl *gomock.Controller) *MockIRoleRepository {
	mock := &MockIRoleRepository{ctrl: ctrl}
	mock.recorder = &MockIRoleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (_m *MockIRoleRepository) EXPECT() *MockIRoleRepositoryMockRecorder {
	return _m.recorder
}

// GetByName mocks base method
func (_m *MockIRoleRepository) GetByName(name string) (*models.Role, error) {
	ret := _m.ctrl.Call(_m, "GetByName", name)
	ret0, _ := ret[0].(*models.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName
func (_mr *MockIRoleRepositoryMockRecorder) GetByName(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "GetByName", reflect.TypeOf((*MockIRoleRepository)(nil).GetByName), arg0)
}

// Create mocks base method
func (_m *MockIRoleRepository) Create(role *models.Role) error {
	ret := _m.ctrl.Call(_m, "Create", role)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (_mr *MockIRoleRepositoryMockRecorder) Create(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCallWithMethodType(_mr.mock, "Create", reflect.TypeOf((*MockIRoleRepository)(nil).Create), arg0)
}
